ajout travaux pratiques

diff --git a/projet-todos/.github/workflows/build.yml b/projet-todos/.github/workflows/build.yml
--- a/projet-todos/.github/workflows/build.yml
+++ b/projet-todos/.github/workflows/build.yml
@@ -44,24 +44,32 @@ jobs:
       - name: Integration Testing
         run: mvn test -Pit
 
-#      - name: Quality Gate
-#        #votre travail
-#        #adapter : peut utiliser sonarcloud ou une instance distante
-#        run: mvn clean verify sonar:sonar -Dsonar.organization=ept-git -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=seenibu_poc-todos
+      - name: Quality Gate
+        #votre travail
+        #adapter : peut utiliser sonarcloud ou une instance distante
+        run: mvn clean verify sonar:sonar -Dsonar.organization=ept-git -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=seenibu_poc-todos
+
       - name: Check Quality Gate
         run: |
           echo "Checking Quality Gate status..."
-          curl -X GET \
-            -u "${{ secrets.SONAR_TOKEN }}:" \
+          # Appeler l'API de SonarCloud pour obtenir le statut de la Quality Gate
+          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" \
             "https://sonarcloud.io/api/qualitygates/project_status?projectKey=seenibu_poc-todos" \
             -o quality_gate_status.json
-          jq -r '.projectStatus.status' quality_gate_status.json
-        continue-on-error: true  # Continuer même si la vérification échoue pour afficher le statut
+          # Extraire le statut de la Quality Gate en utilisant jq
+          QUALITY_STATUS=$(jq -r '.projectStatus.status' quality_gate_status.json)
+          echo "Quality Gate status: $QUALITY_STATUS"
+          # Vérifier si la Quality Gate a échoué
+          if [ "$QUALITY_STATUS" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
+      
 
-      - name: Check Quality Gate
-        #votre travail
-        #verifier si la Quality Gate is ok
-        run: echo "Checking quality gate ... "
+      #      - name: Check Quality Gate
+#        #votre travail
+#        #verifier si la Quality Gate is ok
+#        run: echo "Checking quality gate ... "
 
       - name: Package
         run: mvn -B package  -DskipTests=true
