second test2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -94,19 +94,30 @@ jobs:
         run: |
           docker push --all-tags  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}
 
-#      - name: Deploy to Dev
-#        #votre travail
-#        #se connecter a un serveur distant et deployer l'image docker que vous venez de builder
-#        run: echo " 1) Login to my remote server ...\n 2) Stop docker container if running ... \n 3) Pull latest version and run it ... "
-#
-#      - name: Wait for deploy to finish
-#        #votre travail
-#        run: echo "Wait 30s ... "
-#
-#      - name: Check deploy
-#        #verifier si le deploiement s'est bien passe
-#        #votre travail
-#        run: echo " 1) Run Get request <my_server_ip:my_port/cicd/_health> to check if service is running ...\n 2) Get request should return 200 with content <Welcome to my Todo app> ..."
-#
-#
+      - name: Deploy to Dev
+        run: |
+            echo "1) Login to my remote server ..."
+            ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} -p ${{ secrets.REMOTE_PORT }} << EOF
+              echo "2) Stop docker container if running ..."
+              docker stop myapp || true
+              docker rm myapp || true
+              echo "3) Pull latest version and run it ..."
+              docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE}}:latest
+              docker run -d --name myapp -p 80:80 ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE}}:latest
+            EOF
+      - name: Wait for deploy to finish
+        #votre travail
+        run: sleep 30
+
+      - name: Check deploy
+        run: |
+          echo "1) Run Get request <my_server_ip:my_port/cicd/_health> to check if service is running ..."
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.REMOTE_HOST }}:80/cicd/_health)
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "Deploy failed!"
+            exit 1
+          else
+            echo "Deploy succeeded! Service is running."
+          fi
+
 
