second test3

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -101,14 +101,17 @@ jobs:
 
       - name: Check deploy
         run: |
-          echo "1) Run Get request to check if service is running..."
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://68.221.168.79:80/cicd/_health)
-          if [ "$RESPONSE" -ne 200 ]; then
-            echo "Deploy failed!"
-            exit 1
-          else
-            echo "Deploy succeeded! Service is running."
-          fi
+          echo "1) Run GET request to check if service is running..."
+          ssh -o StrictHostKeyChecking=no -i kira.pem ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
+            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:80/cicd/_health)
+            echo "HTTP response code: $RESPONSE"
+            if [ "$RESPONSE" -ne 200 ]; then
+              echo "Deploy failed!"
+              exit 1
+            else
+              echo "Deploy succeeded! Service is running."
+            fi
+          EOF
         shell: /usr/bin/bash -e {0}
         env:
           JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.11-9/x64
