second test2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -84,41 +84,41 @@ jobs:
         run: |
           docker login -u=${{secrets.DOCKER_USERNAME}} -p=${{ secrets.DOCKER_TOKEN}} docker.io
 
-      - name: Build Docker image
-        run: |
-          docker build -t  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }} -t  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}:latest  .   
-
-      - name: Publish Docker image versions
-        run: |
-          docker push --all-tags  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}
-
-      - name: Deploy to Dev
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
-          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
-          if [ $(docker ps -q -f name=myapp) ]; then
-            docker stop myapp && docker rm myapp
-          fi
-          docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
-          EOF
-
-      - name: Wait for deploy to finish
-        run: sleep 30
-
-      - name: Check deploy
-        run: |
-          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
-          if [ $RESPONSE -ne 200 ]; then
-            echo "Deployment failed!"
-            exit 1
-          else
-            CONTENT=$(curl -s http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
-            if [[ $CONTENT == *"Welcome to my Todo app"* ]]; then
-              echo "Deployment successful!"
-            else
-              echo "Unexpected content: $CONTENT"
-              exit 1
-            fi
-      
-
-
+#      - name: Build Docker image
+#        run: |
+#          docker build -t  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}:${{ github.sha }} -t  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}:latest  .
+#
+#      - name: Publish Docker image versions
+#        run: |
+#          docker push --all-tags  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}
+#
+#      - name: Deploy to Dev
+#        run: |
+#          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
+#          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
+#          if [ $(docker ps -q -f name=myapp) ]; then
+#            docker stop myapp && docker rm myapp
+#          fi
+#          docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
+#          EOF
+#
+#      - name: Wait for deploy to finish
+#        run: sleep 30
+#
+#      - name: Check deploy
+#        run: |
+#          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
+#          if [ $RESPONSE -ne 200 ]; then
+#            echo "Deployment failed!"
+#            exit 1
+#          else
+#            CONTENT=$(curl -s http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
+#            if [[ $CONTENT == *"Welcome to my Todo app"* ]]; then
+#              echo "Deployment successful!"
+#            else
+#              echo "Unexpected content: $CONTENT"
+#              exit 1
+#            fi
+#
+#
+#
