second test2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -93,18 +93,32 @@ jobs:
           docker push --all-tags  ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_REGISTRY_IMAGE }}
 
       - name: Deploy to Dev
-        #votre travail
-        #se connecter a un serveur distant et deployer l'image docker que vous venez de builder
-        run: echo " 1) Login to my remote server ...\n 2) Stop docker container if running ... \n 3) Pull latest version and run it ... "
+        run: |
+          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
+          docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
+          if [ $(docker ps -q -f name=myapp) ]; then
+            docker stop myapp && docker rm myapp
+          fi
+          docker run -d --name myapp -p 80:80 ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REGISTRY_IMAGE }}:latest
+          EOF
 
       - name: Wait for deploy to finish
-        #votre travail
-        run: echo "Wait 30s ... "
+        run: sleep 30
 
       - name: Check deploy
-        #verifier si le deploiement s'est bien passe
-        #votre travail
-        run: echo " 1) Run Get request <my_server_ip:my_port/cicd/_health> to check if service is running ...\n 2) Get request should return 200 with content <Welcome to my Todo app> ..."
-
+        run: |
+          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
+          if [ $RESPONSE -ne 200 ]; then
+            echo "Deployment failed!"
+            exit 1
+          else
+            CONTENT=$(curl -s http://${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PORT }}/cicd/_health)
+            if [[ $CONTENT == *"Welcome to my Todo app"* ]]; then
+              echo "Deployment successful!"
+            else
+              echo "Unexpected content: $CONTENT"
+              exit 1
+            fi
+      
 
 
diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -50,4 +50,17 @@ jobs:
         run:  mvn clean verify sonar:sonar -Dsonar.organization=lykarim -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }} -Dsonar.projectKey=Lykarim_gestiondeprojetagile
 
       - name: Check Quality Gate
-        run: echo "Checking if quality gate is met ... "
+        run: |
+          echo "Checking Quality Gate status..."
+          # Appeler l'API de SonarCloud pour obtenir le statut de la Quality Gate
+          curl -X GET -u "${{ secrets.SONAR_TOKEN }}:" \
+            "https://sonarcloud.io/api/qualitygates/project_status?projectKey=seenibu_poc-todos" \
+            -o quality_gate_status.json
+          # Extraire le statut de la Quality Gate en utilisant jq
+          QUALITY_STATUS=$(jq -r '.projectStatus.status' quality_gate_status.json)
+          echo "Quality Gate status: $QUALITY_STATUS"
+          # Vérifier si la Quality Gate a échoué
+          if [ "$QUALITY_STATUS" != "OK" ]; then
+            echo "Quality Gate failed!"
+            exit 1
+          fi
